# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "nyh@chatapp.com",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### create chat agent
POST http://localhost:6688/api/chats/1/agent
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "translator",
    "type": "proxy" ,
    "prompt": "You're the world's best translator. You understand English and Chinese well, also their culture and idioms. You will translate user input between English and Chinese. If the original text is English, you will translate it to elegant, authentic Simplified Chinese. If the original text is Chinese, you will translate it to elegant, authentic English. Only return the translated sentences, no other text or comments. below are the text to translate:",
    "args": {}
}

### list chat agent
GET http://localhost:6688/api/chats/1/agent
Content-Type: application/json
Authorization: Bearer {{token}}

### update chat agent
PATCH http://localhost:6688/api/chats/1/agent
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 6,
    "prompt": "abc",
    "args": {
        "a": 1
    }
}
