# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "nyh@chatapp.com",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### upload files

POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="avatar.png"
Content-Type: application/octet-stream

< e:\Users\ASUS\Desktop\pic\2020122718461226960.jpg
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

###
GET http://localhost:6688/api/files/1/1e2/078/862bd199a443a09348c11e463c80527905.png
Authorization: Bearer {{token}}


###
GET http://localhost:6688/api/files/1/1e2/078/862bd199a443a09348c11e463c80527905.png?access_token={{token}}
